src/styles/styles.scss
=> fix: issue where links were blue when not visited.

src/app/app.module.ts, src/app/fields/form/form.component.html, src/app/fields/form/form.component.scss, src/app/fields/form/form.component.spec.ts, src/app/fields/form/form.component.ts, src/app/fields/input/input.component.html, src/app/fields/input/input.component.spec.ts, src/app/fields/input/input.component.ts, src/app/fields/models.ts, src/app/fields/radio/radio.component.html, src/app/fields/radio/radio.component.scss, src/app/fields/radio/radio.component.spec.ts, src/app/fields/radio/radio.component.ts, src/app/fields/select/select.component.html, src/app/fields/select/select.component.spec.ts, src/app/fields/select/select.component.ts, src/app/fields/textarea/textarea.component.html, src/app/fields/textarea/textarea.component.spec.ts, src/app/fields/textarea/textarea.component.ts, src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts, src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.html, src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.scss, src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.ts, src/styles/styles.scss
=> feat: Added a dynamic form field system from manifest data

src/app/fields/input/input.component.ts, src/app/fields/models.ts, src/app/fields/radio/radio.component.ts, src/app/fields/select/select.component.ts, src/app/fields/textarea/textarea.component.ts
This reverts commit 25f57b0374c873458ea2fc7d617c123a35b25517.
=> Revert "fix: removed required"

src/app/fields/form/form.component.html, src/app/fields/form/form.component.scss, src/app/fields/input/input.component.html, src/app/fields/models.ts, src/app/fields/radio/radio.component.html, src/app/fields/select/select.component.html, src/app/fields/textarea/textarea.component.html, src/app/manifest-dag-editor/manifest-dag-editor.component.html, src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.html, src/styles/styles.scss
=> feature: added displayName and hint to form fields.

src/app/container-logs/logs.component.ts
=> Fix/onepanel.core 229.log.lines.added.at.cursor

src/app/workflow/workflow.service.ts
…ore explicit about intent and having a value less likely reached.
=> fix: Changed arbitrary large value to Number.MAX_SAFE_INTEGER

src/app/app.module.ts, src/app/node-info/artifact-parameter/artifact-parameter.component.html, src/app/node-info/artifact-parameter/artifact-parameter.component.spec.ts, src/app/node-info/artifact-parameter/artifact-parameter.component.ts, src/app/node-info/node-info.component.html, src/app/node-info/node-info.component.ts
=> feat: added artifacts to be display under parameters for node info.

src/app/auth/auth.guard.ts, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.html, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.ts, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts
=> Fix/onepanelio.core.251 workspace.templates

src/app/cron-workflow/cron-workflow-list/cron-workflow-list.component.ts, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts
=> Fix.onepanelio.core.252 missing.confirmation.dialogs

src/app/app.component.html
=> fix: issue where docs were selected when settings were

src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.ts, src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.ts
=> Fix/onepanelio.core.289 parameters.always.strings

src/app/workflow/workflow-executions-list/workflow-executions-list.component.html, src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts
Adds the workflow template version to the list of workflow executions
Fixes onepanelio/core#147
This also needs the corresponding API PR.
=> feat: added workflow template versions to workflow executions list.

src/app/workflow-template/workflow-template-view/workflow-template-view.component.html, src/app/workflow/workflow-executions-list/workflow-executions-list.component.html
/kind bug
It makes version display consistent with other dates like Created, Modified, Started and Finished.
Fixes onepanelio/core#313
These changes are all on Workflow Template details page.
=> fix: make version display consistent

src/app/manifest-dag-editor/manifest-dag-editor.component.html, src/app/manifest-dag-editor/manifest-dag-editor.component.scss, src/app/manifest-dag-editor/manifest-dag-editor.component.ts
Allows text editor component to expand the width.
Fixes onepanelio/core#315
=> feature: allow expanding text editor

src/app/auth/auth.guard.ts, src/app/auth/auth.service.ts, src/app/auth/login/login.component.html, src/app/auth/login/login.component.ts, src/app/router/app-router.service.ts
* Fixed issue where login was not redirecting to the referer
* Fixed issue where Token in login UI was cut off when it was a label over the input
* Updated login button indicate loading (when network request is being made)
Fixes onepanelio/core#334
=> fix: login redirect

src/app/workflow-template/workflow-template.component.html, src/app/workflow-template/workflow-template.component.scss, src/app/workflow-template/workflow-template.component.ts
Fix issue where workflows headers and content were not aligned.
Fixes onepanelio/core#336
=> fix: issue where workflow template headers and content were not aligned

src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts
Fixes an issue where no workflow executions caused a crash when viewing the workflow executions for a workflow template.
Fixes onepanelio/core#347
=> fix: issue where no workflow executions caused a crash.

src/app/workflow-template/workflow-template.component.html, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.html, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.ts, src/app/workspace/workspace-view/workspace-view.component.html, src/app/workspace/workspace-view/workspace-view.component.scss, src/app/workspace/workspace-view/workspace-view.component.ts
- Disable node pool update if no access
- Change "Open" to "View" in Workflows
=> fix: Disable node pool update if no access

src/app/workflow-template/workflow-template.component.html, src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts, src/app/workflow/workflow.component.ts, src/app/workspace/workspace-info/workspace-identifier/workspace-identifier.component.ts, src/app/workspace/workspace-status/workspace-status-bar/workspace-status-bar.component.ts, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.html, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.ts, src/app/workspace/workspace-view/workspace-view.component.html, src/app/workspace/workspace-view/workspace-view.component.scss, src/app/workspace/workspace-view/workspace-view.component.ts, src/app/workspace/workspace.component.ts
Updates auth checks to check against new Workspace CRD
Fixes onepanelio/core#360
=> feat: Update auth checks to check against new Workspace CRD

src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html, src/styles/font-variables.scss
Adds a link to [Workspace template repository](https://github.com/onepanelio/templates/tree/master/workspaces)
=> feat: Add link to workspace templates repository

src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.html, src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts
Adds a loading spinner next to workflow templates title in the edit workflow templates page
Fixes onepanelio/core#459
=> feat: added loading indicator to workflow templates while network requests are being made

src/app/container-logs/logs.component.scss
Fixes issue where invalid characters in logs had a pink background color.
Fixes onepanelio/core#468
=> fix: issue where invalid characters had a pink background color

src/app/fields/input/input.component.html, src/app/fields/radio/radio.component.html, src/app/fields/select/select.component.html, src/app/fields/textarea/textarea.component.html
This allows hints to contain HTML. Example:
=> feat: Support HTML in hints

Makefile, src/api/README.md, src/api/api.module.ts, src/api/api/authService.service.ts, src/api/api/configService.service.ts, src/api/api/cronWorkflowService.service.ts, src/api/api/labelService.service.ts, src/api/api/namespaceService.service.ts, src/api/api/secretService.service.ts, src/api/api/serviceService.service.ts, src/api/api/workflowService.service.ts, src/api/api/workflowTemplateService.service.ts, src/api/api/workspaceService.service.ts, src/api/api/workspaceTemplateService.service.ts, src/api/encoder.ts, src/api/model/workspaceTemplate.ts, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.html, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.scss, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.ts, src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.html, src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.scss, src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.ts, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.html, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.scss
Adds description to workspace templates 
Fixes onepanelio/core#470
=> feat: Add description UI element for workspace templates

src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.html, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.scss, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.ts
=> feat: increase workspace template heights and set default description

src/app/app.component.html, src/app/app.component.ts
Conditionally display services in UI
Fixes onepanelio/core#516
=> feat: conditionally display services in UI

src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.html
Fix issue where default description for workspace templates was nginx.
Fixes onepanelio/core#525
=> fix: issue where default description for workspace templates was nginx

src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.ts, src/app/workflow/workflow.component.html, src/app/workflow/workflow.component.ts
Updates "re-run" for workflows to allow the user to change the parameters.
Fixes onepanelio/core#404
To test:
* Create a workflow template with parameters
* Start the workflow
* Terminate it
* Rerun with new parameter values
=> feat: added parameters to run again so you can change on a re-run

src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.ts, src/app/workflow/workflow.component.ts
=> fix: issue where labels were not being loaded in re-run

pocs/dag-ui/package-lock.json, pocs/dag-ui/package.json
=> chore: update poc/dag-ui packages

src/app/workflow-template-select/workflow-template-select.component.ts, src/app/workflow-template/workflow-template-create/workflow-template-create.component.ts, src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.ts
Updates the sample templates listed in create workflow template.
Fixes onepanelio/core#587
=> feat: update default templates for workflow templates

src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts
Fixes a bug where WorkflowTemplate was missing labels, causing issues with building an image.
=> fix: bug where code was missing labels for Workflow Template

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.html, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.scss, src/app/workflow-template/workflow-template-view/workflow-template-view.component.scss
Adjusts the UI associated with workflow executions dashboard
Fixes onepanelio/core#604
=> feat: adjust workflow dashboard call to action

src/app/workflow-template-select/workflow-template-select.component.ts
Updates the names for the sample workflows.
Fixes onepanelio/core#603
=> fix: names for sample workflows

src/app/workspace/workspace.component.ts
Fixes issue where terminating all workspaces did not update the UI - one workspace would still be shown.
Fixes onepanelio/core#605
To view fix:
Note: It is recommended you try this on the current master branch to see the issue and then on this branch to see the fix.
* Create two or more workspaces
* Wait for them to launch
* Terminate one by one (wait for them to finish terminating) until you are on the last one.
* Verify the list is empty
=> fix: issue where workspaces did not update when all were termianted

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.ts, src/app/ui-tools/stat-bar/stat-bar.component.ts
Fix issue where workflow execution statistics did not always display.
=> fix: issue where workflow execution statistics did not always display

.github/PULL_REQUEST_TEMPLATE.md
Updates the PR template to include a checklist.
=> feat: update PR template to include checklist

src/api/api/workspaceTemplateService.service.ts, src/app/router/app-router.service.ts, src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.ts, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.html, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.ts
Add share link functionality for workspace templates.
Fixes onepanelio/core#299
**Checklist**
Required
=> feat: share link functionality for workspace templates

src/app/navbar/navbar.component.ts, src/app/workspace/workspace-view/workspace-view.component.ts
Updates the page title when a specific tab is selected.
Fixes onepanelio/core#620
**Checklist**
Required
=> feat: update titles for tab selected

src/app/dashboard/dashboard-workspace/dashboard-workspace.component.ts, src/app/workspace/workspaces/workspaces.component.ts
Fixes an issue where no workspace data did not display a call to action.
**Checklist**
Required
=> fix: issue where no workspace data did not display a call to action

src/app/auth/login/login.component.ts, src/app/dashboard/dashboard-workspace/dashboard-workspace.component.ts
Fixes issue where workspace statistics showed all 0s
**Checklist**
Required
=> fix: issue where workspace statistics showed all 0s

.github/workflows/push_tag.yaml
=> feat: push up a new build based on tag name

src/app/workflow-template/workflow-template.component.html
Adds a "Back to workflows" link to workflow templates page
**Checklist**
Required
=> feat: add back to workflows link to workflow templates page

src/app/workflow/workflow-view/workflow-view.component.ts
Fixes group for workflows resource
**Checklist**
Required
=> fix: Fix group for workflows resource

src/api/model/isValidTokenResponse.ts, src/app/auth/login/login.component.ts
Revert jwt api auth changes
**Checklist**
Required
=> feat: revert jwt api auth changes

src/app/app.module.ts, src/app/auth/login/login.component.ts, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.html, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.ts, src/app/ui-tools/work-status/work-status.component.html, src/app/ui-tools/work-status/work-status.component.scss, src/app/ui-tools/work-status/work-status.component.spec.ts, src/app/ui-tools/work-status/work-status.component.ts, src/app/workflow/workflow-executions-list/workflow-executions-list.component.html, src/app/workflow/workflow-executions-list/workflow-executions-list.component.scss, src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts, src/app/workflow/workflow-executions/workflow-executions.component.ts, src/app/workflow/workflow.component.html, src/app/workflow/workflow.component.ts, src/app/workspace/workspace-list/workspace-list.component.html, src/app/workspace/workspace-status/workspace-phase-icon/workspace-phase-icon.component.scss, src/app/workspace/workspace-status/workspace-status.component.html, src/app/workspace/workspace-status/workspace-status.component.scss, src/app/workspace/workspace-status/workspace-status.component.ts, src/styles/flex-styles.scss
Adds labels to workflow listing.
**Checklist**
Required
=> feat: add labels to workflow listing

src/app/workflow/workflow-executions-list/workflow-executions-list.component.scss
=> fix: add top margin to workflow labels

src/app/node-info/node-info.component.ts, src/app/services/service-list/service-list.component.html, src/app/workflow-template/workflow-template-view/workflow-template-view.component.html, src/app/workflow-template/workflow-template.component.html, src/app/workflow/workflow-executions-list/workflow-executions-list.component.html, src/app/workflow/workflow-view/workflow-view.component.html, src/app/workspace/workspace-info/workspace-identifier/workspace-identifier.component.html, src/app/workspace/workspace-list/workspace-list.component.html, src/styles/styles.scss
Reduces the size of view/edit buttons
**Checklist**
Required
=> feat: reduce size of view/edit buttons

src/app/node-info/node-info.component.ts
=> fix: artifact display issues

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/error/error.component.html, src/app/error/error.component.scss, src/app/error/error.component.spec.ts, src/app/error/error.component.ts, src/app/permissions/permission.service.ts, src/app/permissions/permissions.service.spec.ts, src/app/router/app-router.service.ts, src/app/workflow/workflow-executions-list/workflow-executions-list.component.html, src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts, src/app/workflow/workflow-view/workflow-view.component.ts, src/app/workspace/workspace-list/workspace-list.component.ts, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.html, src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.ts, src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.html, src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.ts, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.html, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.ts, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.ts, src/app/workspace/workspace.component.html, src/app/workspace/workspace.component.ts
Adds an error page for permission failures that require a separate page.
Also adds a permissions dedicated service and adds some missing permissions checks.
Fixes onepanelio/core#373
**Checklist**
Required
=> feat: added error page and centralized permissions logic into a service.

src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.ts, src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.ts
Fixes an issue where editing a workspace template's description didn't always save it correctly.
Fixes onepanelio/core#687
**Checklist**
Required
=> fix: issue with saving workspace template description

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.html, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.ts, src/app/dashboard/dashboard-workspace/dashboard-workspace.component.html, src/app/dashboard/dashboard-workspace/dashboard-workspace.component.ts, src/app/workflow-template/workflow-template-view/workflow-template-view.component.html, src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts, src/app/workflow-template/workflow-template.component.html, src/app/workflow-template/workflow-template.component.scss, src/app/workflow-template/workflow-template.component.ts, src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts, src/app/workflow/workflow-executions/workflow-executions.component.html, src/app/workflow/workflow-executions/workflow-executions.component.scss, src/app/workflow/workflow-executions/workflow-executions.component.ts, src/app/workflow/workflow.component.html, src/app/workflow/workflow.component.ts, src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html, src/app/workspace/workspace.component.html, src/app/workspace/workspace.component.ts, src/app/workspace/workspaces/workspaces.component.html, src/app/workspace/workspaces/workspaces.component.scss, src/app/workspace/workspaces/workspaces.component.ts
Fixes issue where workflow, workflow templates, and workspaces page listings had issues with content sometimes not displaying, including the filter bar and lack of "no content" messages.
Fixes onepanelio/core#692
**Checklist**
Required
=> feat: fix display issues with listing pages

src/app/permissions/permission.service.ts
Fixes wrong namespaces being used for permissions request
**Checklist**
Required
=> fix: wrong namespace for permissions request

src/app/workflow-template/workflow-template.component.html
Add space between executions number and label
**Checklist**
Required
=> fix: Add space between executions number and label

src/app/workflow-template/workflow-template.component.ts, src/app/workflow/workflow-executions/workflow-executions.component.ts, src/app/workspace/workspaces/workspaces.component.ts
=> fix: issue where adding workspaces did not show a new workspace

src/app/dag/dag.component.scss, src/app/node-info/metrics/metrics.component.html, src/app/node-info/metrics/metrics.component.ts, src/app/node-info/node-info.component.html, src/app/node-info/node-info.component.scss, src/app/node-info/parameter/parameter.component.html, src/app/node/node.service.ts, src/app/workflow-template/workflow-template.service.ts
=> feat: Update task info panel

src/app/metrics/metrics-edit/metrics-edit.component.html, src/app/metrics/metrics-edit/metrics-edit.component.ts
=> fix: compilation issue with mat options

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.scss, src/app/metrics/metrics-edit-dialog/metrics-edit-dialog.component.ts, src/app/workflow/workflow-executions-list/workflow-executions-list.component.html, src/app/workflow/workflow-view/workflow-view.component.html, src/app/workflow/workflow-view/workflow-view.component.ts
=> fix: metrics UI display issues

src/app/workflow/workflow-view/workflow-view.component.html
=> fix: regression where workflow info node was embedded instead of separate

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.scss, src/app/workflow-template/workflow-template-view/workflow-template-view.component.scss, src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts, src/app/workflow/workflow.component.scss
=> feat: Hide columns so that metrics is display before templates

src/app/workflow/workflow-view/workflow-view.component.ts
=> feat: update workflow metrics when workflow completes

src/app/workflow/workflow-parameter/workflow-parameter.component.scss
Recognize new lines in param values
**Checklist**
Required
=> style: Recognize new lines in param values

.github/workflows/push_tag.yaml
Fixes onepanelio/core#743
**Checklist**
Required
=> fix: github actions breaking

src/app/pipes/phase-image/phase-image.pipe.ts, src/app/pipes/phase-translate/phase-translate.pipe.ts, src/app/status/status.component.ts, src/app/workflow-template/workflow-template.service.ts, src/app/workflow/workflow.service.ts
Supports handling of Omitted workflow phase.
Fixes onepanelio/core#745
**Checklist**
Required
=> fix: added missing Omitted workflow phase

src/app/workflow/workflow-view/workflow-view.component.html
Adds a link to the workflow template from a workflow execution page
Fixes onepanelio/core#758
**Checklist**
Required
=> feat: added workflow template link in workflow execution page

src/api/model/listWorkflowExecutionsResponse.ts, src/api/model/listWorkflowTemplatesResponse.ts, src/api/model/listWorkspaceResponse.ts, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.html, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.ts, src/app/dashboard/dashboard-workspace/dashboard-workspace.component.html, src/app/dashboard/dashboard-workspace/dashboard-workspace.component.ts, src/app/workflow-template/workflow-template-view/workflow-template-view.component.html, src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts, src/app/workflow-template/workflow-template.component.html, src/app/workflow-template/workflow-template.component.ts, src/app/workflow/workflow-executions/workflow-executions.component.html, src/app/workflow/workflow-executions/workflow-executions.component.ts, src/app/workflow/workflow.component.html, src/app/workflow/workflow.component.ts, src/app/workspace/workspace-list/workspace-list.component.ts, src/app/workspace/workspace.component.html, src/app/workspace/workspace.component.ts, src/app/workspace/workspaces/workspaces.component.html, src/app/workspace/workspaces/workspaces.component.ts
In combination with https://github.com/onepanelio/core/pull/765
this PR simplifies the logic for listing workflows, workspaces, and workflow templates. It fixes issues where the call to action can sometimes show for a split second before disappearing.
**Checklist**
Required
=> feat: simplify logic for listing resources

src/app/clock/clock.component.ts, src/app/dashboard/dashboard-workflow/dashboard-workflow.component.ts, src/app/workflow/workflow-executions/workflow-executions.component.ts, src/app/workspace/workspace-status/launching-timer/launching-timer.component.ts, src/app/workspace/workspaces/workspaces.component.ts
Fixes an issue where some intervals might not have been cleared in core-ui version.
**Checklist**
Required
=> fix: issues where some intervals might not have been cleared.

src/app/workflow/workflow-view/workflow-view.component.html
Fixes an issue where node info content was overflowing the rounded corners ever so slightly.
**Checklist**
Required
=> fix: issue where node info corners were overflowing 

src/app/router/app-router.service.ts, src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts, src/app/workflow/workflow-view/workflow-view.component.ts
Fixes onepanelio/core#761
**Checklist**
Required
=> fix: issue where back link sometimes didn't work in workflows

src/app/router/app-router.service.ts
=> fix: issue where back navigation didn't work correctly with query parameters

src/app/files/file-viewer/text-file-view/text-file-view.component.ts
=> fix: issue where json or yaml text was not rendered

src/app/app.component.ts, src/app/files/file-viewer/text-file-view/text-file-view.component.html, src/app/files/file-viewer/text-file-view/text-file-view.component.ts
=> feat: pretty-print json files in output artifacts

src/app/workflow/workflow-executions-list/workflow-executions-list.component.html
Display "no metrics" when there are none
**Checklist**
Required
=> feat: display "no metrics" when there are none

src/app/fields/input/input.component.html, src/app/fields/input/input.component.ts, src/app/fields/radio/radio.component.html, src/app/fields/radio/radio.component.ts, src/app/fields/select/select.component.html, src/app/fields/select/select.component.ts, src/app/fields/textarea/textarea.component.html, src/app/fields/textarea/textarea.component.ts
=> fix: updated fields to use reactive forms data communication

src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts
=> fix: missing error messages from workspace templates

src/app/fields/form/form.component.ts
=> fix: issue where form was not cleared when switching workflow template.

src/app/fields/textarea/textarea.component.ts
=> fix: issue where text area no longer had a value.

src/app/container-logs/logs.component.ts
=> fix: issue where no timestamp created an extra space in logs

src/app/manifest-dag-editor/manifest-dag-editor.component.ts
=> fix: issue where error usually didn't disappear for workflow template editor

.github/workflows/push_master_branch.yaml
=> feat: rename dev to "latest" when pushing up master

src/app/alert/alert.service.ts, src/app/alert/alert.ts, src/app/permissions/permission.service.ts, src/app/router/app-router.service.ts, src/app/secrets/create-secret/create-secret.component.html, src/app/secrets/create-secret/create-secret.component.ts, src/app/secrets/edit-secret/edit-secret.component.html, src/app/secrets/edit-secret/edit-secret.component.ts, src/app/secrets/secret-list/secret-list.component.html, src/app/secrets/secret-list/secret-list.component.scss, src/app/secrets/secret-list/secret-list.component.ts, src/app/secrets/secrets.component.html, src/app/secrets/secrets.component.scss, src/app/secrets/secrets.component.ts
=> feat: add permissions checks to secrets UI

src/app/workflow-template-select/workflow-template-select.component.ts
=> feat: Better hyperparameter turning starter template

src/app/workflow-template-select/workflow-template-select.component.ts
=> fix: Fix CVAT training template

src/app/files/file-browser/file-browser.component.html, src/app/files/file-browser/file-browser.component.ts, src/app/node-info/node-info.component.html
=> feat: added path copying to workflow artifact output viewer

src/app/files/file-browser/file-browser.component.ts, src/app/node-info/node-info.component.html
=> chore: removed unused code with file copy 

src/app/file-sync/file-sync.component.ts, src/app/files/file-browser-dialog/file-browser-dialog.component.html, src/app/files/file-browser-dialog/file-browser-dialog.component.ts, src/app/files/file-browser/file-browser.component.html, src/app/files/file-browser/file-browser.component.ts, src/app/workspace/workspace-view/workspace-view.component.html, src/app/workspace/workspace-view/workspace-view.component.scss, src/app/workspace/workspace-view/workspace-view.component.ts
=> chore: Remove leading slash

src/app/app.module.ts, src/app/file-sync/file-sync.component.html, src/app/file-sync/file-sync.component.scss, src/app/file-sync/file-sync.component.ts, src/app/files/file-browser/file-browser.component.ts, src/app/files/prefix-file-input/prefix-file-input.component.html, src/app/files/prefix-file-input/prefix-file-input.component.scss, src/app/files/prefix-file-input/prefix-file-input.component.spec.ts, src/app/files/prefix-file-input/prefix-file-input.component.ts, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.html, src/app/workspace/workspace-view/workspace-view-parameters/workspace-view-parameters.component.scss
=> fix: remove leading slash in ui

src/api/api/configService.service.ts, src/api/api/workspaceService.service.ts, src/api/model/getConfigResponse.ts, src/api/model/getNamespaceConfigResponse.ts, src/api/model/models.ts, src/app/breadcrumbs/breadcrumbs.component.ts, src/app/file-sync/file-sync.component.ts, src/app/files/file-browser-dialog/file-browser-dialog.component.html, src/app/files/file-browser-dialog/file-browser-dialog.component.ts, src/app/files/file-browser/file-browser.component.html, src/app/files/file-browser/file-browser.component.ts
=> feat: Add bucket prefix to file sync

src/app/file-sync/file-sync.component.ts, src/app/files/prefix-file-input/prefix-file-input.component.ts
=> feat: use start time from api

src/app/file-sync/file-sync.component.ts
=> chore: rename start -> timestamp based on API update

src/app/file-sync/file-sync.component.ts
=> fix: incorrect usage of timestamp from file sync

src/app/workflow-template-select/workflow-template-select.component.ts
=> chore: Update hyperparameter tuning template

src/app/file-sync/file-sync.component.ts, src/app/files/file-browser-dialog/file-browser-dialog.component.ts, src/app/files/file-browser/file-browser.component.ts, src/app/files/prefix-file-input/prefix-file-input.component.html, src/app/files/prefix-file-input/prefix-file-input.component.ts
=> fix: file browser removing file paths in root

src/app/file-sync/file-sync.component.html
=> feat: add bucket prefix to object path

src/app/app.component.ts, src/app/files/file-viewer/text-file-view/text-file-view.component.ts
=> feat: add support for xml files

src/app/workflow-template-select/workflow-template-select.component.ts
=> chore: Update CVAT training starter template

src/app/file-sync/file-sync.component.ts, src/app/files/file-browser-dialog/file-browser-dialog.component.html, src/app/files/file-browser-dialog/file-browser-dialog.component.ts, src/app/files/file-browser/file-browser.component.html, src/app/files/file-browser/file-browser.component.scss, src/app/files/file-browser/file-browser.component.ts, src/app/files/fileNavigator.ts, src/app/node-info/node-info.component.html, src/app/node-info/node-info.component.ts, src/app/workflow-template/workflow-template.service.ts, src/app/workflow/workflow-view/workflow-view.component.html, src/app/workflow/workflow-view/workflow-view.component.ts, src/styles/styles.scss
=> feat: Workflow local file browser

src/app/node-info/node-info.component.ts
=> fix: incorrect use of https for filesyncer url

src/app/files/file-browser-dialog/file-browser-dialog.component.ts
=> fix: issue with workspace file browser giving wrong path

src/app/config/config.service.spec.ts, src/app/config/config.service.ts, src/app/workflow/workflow-view/workflow-view.component.ts
=> fix: commit missing files

src/app/workspace/workspace-list/workspace-list.component.scss
=> fix: wrong styling selector for nodepool in workspaces

src/app/app.module.ts, src/app/fields/form/form.component.html, src/app/fields/yaml/yaml.component.html, src/app/fields/yaml/yaml.component.scss, src/app/fields/yaml/yaml.component.spec.ts, src/app/fields/yaml/yaml.component.ts, src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.html
=> feat: added editor.yaml type to display text in a yaml editor

src/app/secrets/create-secret/create-secret.component.html, src/app/secrets/create-secret/create-secret.component.spec.ts, src/app/secrets/create-secret/create-secret.component.ts, src/app/secrets/edit-secret/edit-secret.component.html, src/app/secrets/edit-secret/edit-secret.component.ts
Fixes onepanelio/core#898
**Checklist**
Required
=> fix: remove environment variable length limit

src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.ts, src/app/workspace/workspace-list/workspace-list.component.html, src/app/workspace/workspace.component.ts, src/app/workspace/workspaces/workspaces.component.ts
=> feat: create workspace instantly creates UI element.

src/app/workflow-template-select/workflow-template-select.component.ts
=> feat: Update hyperparam tuning starter template

src/app/node/node.service.ts
closes #92 
**Checklist**
Required
=> fix: alert with no error message

src/app/models/models.component.ts
=> feat: link to model details page

src/api/api/workflowService.service.ts, src/api/model/listFilesResponse.ts, src/app/file-sync/file-sync.component.ts, src/app/files/WorkflowFileApiWrapper.ts, src/app/files/file-api.ts, src/app/files/file-browser-dialog/file-browser-dialog.component.scss, src/app/files/file-browser/file-browser.component.html, src/app/files/file-browser/file-browser.component.scss, src/app/files/file-browser/file-browser.component.ts, src/app/files/file-navigator/file-navigator.component.scss, src/app/files/file-navigator/file-navigator.component.ts, src/app/files/fileNavigator.ts
=> feat: added support for pagination in file browser

src/app/node-info/node-info.component.ts
=> fix: issue where workflow breadcrumbs did not navigate up correctly

src/app/files/fileNavigator.ts
=> fix: issue where navigation past root was possible for workflows

src/api/model/createWorkspaceBody.ts, src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.html, src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.ts
=> feat: add checkbox to allow using full node resources or not for workspaces
