onepanelio/core-ui

src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts
src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.html

1. When you are scheduling a cron workflow the action button says "Schedule" instead of "Execute"
2. The tabs switches to cron workflows and you get a message telling you which one was just scheduled.

feat: Update cron workflows so that

---

src/app/auth/auth.service.ts

closed onepanelio/core#249 
Notes: 
* you might have to refresh upon logging out to see the cookie deleted in chrome.
* you will have to log out and back in to see the log out work as we now store the domain when you log in.

fix: auth cookie deleted on log out.

---

src/app/clock/clock.component.ts
src/app/workspace/workspace-status/workspace-status-bar/workspace-status-bar.component.html

Also removed timer display for all statuses except running and paused.
closed onepanelio/core#297

fix: issue where a pausing workspace showed incorrect paused time.

---

src/app/app-routing.module.ts
src/app/guards/can-deactivate.guard.spec.ts
src/app/guards/can-deactivate.guard.ts
src/app/manifest-dag-editor/manifest-dag-editor.component.html
src/app/manifest-dag-editor/manifest-dag-editor.component.ts
src/app/workflow-template/workflow-template-create/workflow-template-create.component.ts
src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts
src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.html
src/app/workspace/workspace-template/workspace-template-create/workspace-template-create.component.ts
src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.html
src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.ts
src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html
src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts

I add a confirmation dialog when the user leaves the Workspace Template List page and has made changes a workspace template.
**What this PR does / Why do we need it**
The current text editor for Workspace Templates is small, and if you have long lines, you need to scroll left. With a trackpad I scroll left and sometimes go too far and leave the page, going back, and losing all my changes. This PR helps prevent that by adding a confirmation dialog when you leave.
**Which issue(s) this PR fixes**
Fixes onepanelio/core#261
**Special notes for your reviewer**
Use cases to test
Note: leave means navigate away, you can click the `back to workspaces` in the top left to do so.
Note: if you create a template, modify it, undo your changes, we still …

feat: onepanelio.core.261 template.confirm.leave

---

src/app/app-routing.module.ts
src/app/workflow-template/workflow-template-create/workflow-template-create.component.html
src/app/workflow-template/workflow-template-create/workflow-template-create.component.ts
src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.html
src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts

Adds a confirmation dialog when the user leaves a Workflow template create/edit page after changes have been made in the template editor.
Fixes onepanelio/core#311
None

feat: Add confirmation when leaving workflow template create/edit after modified

---

src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.html
src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts

Add a loading indicator to the saving button in Workflow Template Edit page when it is saving.
This helps the user know something is happening and prevents multiple clicks.
Fixes onepanelio/core#320
None.

feat: loading indicator when updating an edited workflow template

---

src/app/workflow-template/workflow-template-create/workflow-template-create.component.ts
src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts

/kind bug
Fixes an issue where a Confirmation Dialog appears when you edit an existing Workflow Template or save a newly created Workflow Template.
Fixes onepanelio/core#319
To reproduce the issue in other branches
**Creating a Workflow Template**
If you select a template, make sure to modify it. Otherwise, the system doesn't see any modifications so lets you save without a dialog.
**Editing a Workflow Template**
Make sure to modify the template then hit save.

fix: confirmation dialog when trying to edit or save a workflow template

---

src/app/app.component.html

Removes the navigation header scroll bars in linux chrome.
Fixes onepanelio/core#337

fix: remove overflow scroll, which is giving the scroll bars.

---

src/app/http-interceptors/permission-interceptor.ts

Show different messages and actions depending on auth errors:
- On 401, displays "You are not logged in" with a "Login" button that takes user to login page
- On 403, displays "Unauthorized" with a "Close" button.

fix: Show different messages and perform different actions depending on auth errors

---

src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.html
src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts
src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.html
src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.scss
src/app/workspace/workspace-template/workspace-template-summary-view/workspace-template-summary-view.component.ts
src/app/workspace/workspace-view/workspace-view.component.ts

Fixes issues where
* deleting a workspace template had no loading indication
* deleting a workspace template left the bottom editor with the old data
Fixes onepanelio/core#367

fix: workspace issues

---

src/app/workspace/workspace-template/workspace-template-list/workspace-template-list.component.ts

Adds error message responses from server when creating/editing a workspace template
Fixes onepanelio/core#366

fix: missing error messages for workspace template create/edit

---

src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.ts

Adds an error message for workspace creation if if the error is not a 409
Fixes onepanelio/core#361
Try a bad name like `600s` and the error message should show up.
This PR should be tested along with https://github.com/onepanelio/core/pull/370

fix: added error message for workspace creation if error is not a 409

---

src/app/workspace/workspace-status/workspace-status-bar/workspace-status-bar.component.html
src/app/workspace/workspace.component.html
src/styles/styles.scss

Disable terminate button while workspaces are pausing or launching in workspace list and view pages.
Fixes onepanelio/core#322

fix: disable terminate button while workspaces are pausing or launching

---

src/app/workspace/workspace-status/workspace-status-bar/workspace-status-bar.component.html
src/app/workspace/workspace.component.html
src/styles/styles.scss

…isable.delete"
This reverts commit 51e67cfd8ab70ff16fd6afe319d9a6483d116486, reversing
changes made to f9c82697cdae45ae7230896c9479cb621086cd59.

fix: revert disable terminate buttons as it is not ready yet.

---

src/app/workflow/workflow.component.ts

Fixes an issue where edit labels button did not show up in workflow executions.
This was due to a missing update permissions request.
This also fixes an issue where the permissions request were for workspaces and not workflows.
Fixes onepanelio/core#403

fix: missing edit labels button in workflow execution

---

src/app/workflow-template/workflow-template-status/workflow-template-status.component.html

Fixes an issue where the status bars for Workflow Template page had failed and terminated swapped.
Fixes onepanelio/core#408
To test this easier, you can modify this line
https://github.com/onepanelio/core-ui/blob/master/src/app/workflow-template/workflow-template-status/workflow-template-status.component.ts#L75
change it to 
```
this.values = [5, 6, 7, 8];
```
this allows you to see what the different bars would look like

fix: template status bars had failed and terminated swapped visually

---

src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.ts

* Fixes an issue where selecting previous versions of a workflow template failed to load the labels.
Fixes onepanelio/core#435

fix: labels failed to load for earlier workflow template versions

---

src/app/workflow-template/workflow-template-view/workflow-template-view.component.html
src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts

Failing to load a workflow template when viewing one now shows a corresponding UI. Before, it just showed a never ending loading indicator.
Fixes onepanelio/core#451

fix: failing to load a workflow template is now indicated in UI

---

src/app/fields/textarea/textarea.component.html
src/app/workspace/workspace.component.ts

* Adds a confirmation dialog to deleting a workspace from the workspace list
* Increases the default textarea size to 5 rows
Fixes onepanelio/core#504

feat: confirm workspace delete and increase default textarea size

---

src/app/fields/form/form.component.html
src/app/fields/form/form.component.scss
src/app/fields/input/input.component.html
src/app/workflow-template/workflow-template-edit/workflow-template-edit.component.html
src/app/workflow-template/workflow-template-view/workflow-template-view.component.html
src/app/workspace/workspace-template/workspace-template-edit/workspace-template-edit.component.html
src/app/workspace/workspace.component.html

Adds uid to ui for workspace and workflow templates
Fixes onepanelio/core#507

feat: add uid to ui for workspace and workflow templates

---

.github/workflows/push_master_branch.yaml

Modifies the github action when master is pushed to so it pushes up a "dev" image and not a "latest" image.

fix: push "dev" image and not "latest" when master is pushed to

---

src/app/workflow/workflow-executions/workflow-executions.component.ts

Fixes an issue where sorting workflows when you have <= the number displayed in the list didn't do anything.
Also changes default sort to be createdAt, which is what is displayed in UI.

fix: issue where workflow sorting didn't always work

---

.github/workflows/push_tag.yaml
src/app/app.component.html
src/app/app.component.ts
src/app/auth/auth.guard.ts
src/app/files/file-browser/file-browser.component.html
src/app/files/file-browser/file-browser.component.scss
src/app/files/file-browser/file-browser.component.ts
src/app/files/file-navigator/file-navigator.component.html
src/app/files/file-navigator/file-navigator.component.ts
src/app/files/file-viewer/big-file-view/big-file-view.component.html
src/app/files/file-viewer/big-file-view/big-file-view.component.ts
src/app/files/file-viewer/generic-file-view/generic-file-view.component.ts
src/app/files/file-viewer/text-file-view/text-file-view.component.ts
src/app/files/fileNavigator.ts
src/app/http-interceptors/index.ts
src/app/namespace/namespace-tracker.service.ts
src/app/navbar/navbar.component.html
src/app/navbar/navbar.component.ts
src/app/node-info/node-info.component.html
src/app/node-info/node-info.component.scss
src/app/node-info/node-info.component.ts
src/app/workflow/workflow-view/workflow-view.component.html
src/app/workflow/workflow-view/workflow-view.component.scss
src/app/workflow/workflow-view/workflow-view.component.ts
src/styles/flex-styles.scss

Increases the size of the node info UI and adds support for multiple artifact file browsers
Fixes onepanelio/core#595
**Checklist**
Required

feat: increase node info size and support multiple artifact file browsers

---

src/app/node-info/node-info.component.ts

Fixes an issue where switching to a node that had not yet launched displayed the old artifacts.
**Checklist**
Required

fix: issue where switching to a not-launched node displayed old artifacts

---

Makefile
angular.json
src/app/app.component.html
src/app/auth/auth.service.ts
src/app/auth/login/login.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Fixes an issue where domain was being set during local development. This caused issues when you were pointing at a live deployment.
Fixes onepanelio/core#685
You can test this by running `ng serve` and logging out and then in. The domain should be correct for cookies.
**Checklist**
Required

fix: no domain for local development

---

src/app/dag/dag.component.scss
src/app/node-info/metrics/metrics.component.html
src/app/node-info/metrics/metrics.component.ts
src/app/node-info/node-info.component.html
src/app/node-info/node-info.component.scss
src/app/node-info/node-info.component.ts
src/app/node-info/parameter/parameter.component.html
src/app/node/node.service.ts
src/app/workflow-template/workflow-template.service.ts
src/app/workflow/workflow-view/workflow-view.component.ts
src/app/workflow/workflow.service.ts
src/styles/styles.scss

feat: Sidecars UI

---

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.scss
src/app/dashboard/dashboard-workspace/dashboard-workspace.component.scss
src/app/navbar/navbar.component.scss
src/app/workflow/workflow.component.scss
src/app/workspace/workspace-list/workspace-list.component.scss

Fixes overflow issues where the "View" button on workflow and workspaces lists would overflow to the next line on certain screen sizes. This is for both the dashboard and the individual listing pages.
This also fixes an issue where the selected namespace section of the navbar would not be flush with the bottom on bigger screen heights.
Fixes onepanelio/core#717
You can test this by using chrome's device toolbar and making it have more/less width. Before this fix the "View" button would overflow on certain widths.
**Checklist**
Required

fix: view overflow on workflows/workspaces lists

---

src/app/dag/dag.component.ts
src/app/workflow/workflow-view/workflow-view.component.ts

The workflow view page now adds a node query parameter to the url when a node is selected.
Also, if you take a url with a node query parameter, the page will scroll that node into view and open the node info panel with that node.
Fixes onepanelio/core#768
**Checklist**
Required

feat: Add support to scroll into view a linked Workflow task

---

src/app/workflow/workflow-executions-list/workflow-executions-list.component.html
src/app/workflow/workflow-executions-list/workflow-executions-list.component.scss
src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts
src/styles/flex-styles.scss

Align workflow execution columns so metrics are flush with the top. 
Also fix issue where metrics all expanded when one was selected to expand. Now it's each individual one.
**Checklist**
Required

fix: align workflow execution columns so metrics are flush top

---

src/app/dashboard/dashboard-workflow/dashboard-workflow.component.html
src/app/dashboard/dashboard-workflow/dashboard-workflow.component.scss
src/app/dashboard/dashboard-workspace/dashboard-workspace.component.html
src/app/dashboard/dashboard-workspace/dashboard-workspace.component.scss
src/app/ui-tools/stat-bar/stat-bar.component.html
src/app/workflow/workflow-executions/workflow-executions.component.html
src/app/workflow/workflow-executions/workflow-executions.component.ts
src/app/workflow/workflow.component.html
src/app/workflow/workflow.component.ts
src/app/workspace/workspaces/workspaces.component.html
src/app/workspace/workspaces/workspaces.component.ts

- Removes Filtering and pagination from Dashboard
- Workspace buttons show/hide depending on permissions
This is the roles to test this with:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: onepanel-cluster-readonly
rules:
- apiGroups:
- ''
resources: ["namespaces"]
verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: onepanel-namespace-readonly
rules:
- apiGroups: [""]
resources: ["services", "configmaps", "pods", "pods/log"]
verbs: ["get", "watch", "list"]
- apiGroups: [""]
resources: ["namespaces", "secrets"]
verbs: ["get", "watch", "list"]
- apiGroups: ["argoproj.io"]
resources: ["workflows", …
```

feat: Dashboard and Workspace permission updates

---

src/app/auth/models.ts
src/app/workflow/workflow.component.ts

Fixes an issue where workflow execute button was sometimes hidden.
Fixes onepanelio/core#825
Before the `create` permission was checked for `workspaces` I combined it into `workflows`. 
**Checklist**
Required

fix: incorrect permissions requested for workflow create

---

src/app/app.module.ts
src/app/cron-workflow/cron-workflow-edit-dialog/cron-workflow-edit-dialog.component.ts
src/app/cron-workflow/cron-workflow-list/cron-workflow-list.component.ts
src/app/manifest-dag-editor/manifest-dag-editor.component.ts
src/app/pipes/date-from-utc/date-from-utc.pipe.spec.ts
src/app/pipes/date-from-utc/date-from-utc.pipe.ts
src/app/router/app-router.service.ts
src/app/workflow-template/workflow-template-view/workflow-template-view.component.ts
src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.html
src/app/workflow/workflow-execute-dialog/workflow-execute-dialog.component.ts
src/app/workflow/workflow-executions-list/workflow-executions-list.component.html
src/app/workflow/workflow-executions-list/workflow-executions-list.component.ts
src/app/workflow/workflow-view/workflow-view.component.html
src/app/workflow/workflow-view/workflow-view.component.ts
src/app/workflow/workflow.component.ts

Adds support to customize a workflow when clicking the "rerun" button in a workflow list.
Also add a loading indicator to indicate when the workflow execution dialog is loading data
**Checklist**
Required

feat: added support to provide parameters for workflow reruns

---

src/app/config/config.service.ts
src/app/node-info/node-info.component.html
src/app/node-info/node-info.component.ts
src/app/workflow-template/workflow-template.service.ts
src/app/workflow/workflow-view/workflow-view.component.html
src/app/workflow/workflow-view/workflow-view.component.ts
src/app/workflow/workflow.service.ts

feat: add node pool label to workflow tasks

---

src/app/node-info/node-info.component.ts
src/app/workflow/workflow-executions/workflow-executions.component.ts

fix: nodepool selector was wrong when it was not a parameter

---

src/app/alert/alert.service.ts
src/app/auth/login/login.component.html
src/app/auth/login/login.component.scss
src/app/auth/login/login.component.ts

Before, any error was shown as the token being wrong. Now, additional errors are displayed accordingly.
Fixes onepanelio/core#895
**Checklist**
Required

feat: add additional error handling for login page

---

src/app/files/WorkflowFileApiWrapper.ts
src/app/files/file-api.ts
src/app/files/file-browser-dialog/file-browser-dialog.component.ts
src/app/files/file-browser/file-browser.component.ts
src/app/files/file-viewer/image-file-view/image-file-view.component.ts
src/app/files/file-viewer/text-file-view/text-file-view.component.ts

Also fixes the following bugs
* downloaded files repeated extension twice
* navigation through breadcrumbs sometimes failed
**Checklist**
Required

feat: improve file download speeds for filesyncer

---

src/app/pipes/workspace-phase-image/workspace-phase-image.pipe.ts
src/app/workspace/workspace-phase-status/workspace-phase-status.pipe.ts

To reproduce this before this fix, create the default nginx template, but don't provide any slack environment variables.
The workspace status icon/state in the listing page will display an error.
**Checklist**
Required

fix: added handling for failed state

---

src/app/app.component.ts
src/app/models/models.component.ts
src/app/namespace-select/namespace-select.component.ts
src/app/namespace/namespace-tracker.service.ts

Fixes onepanelio/core#937
**Checklist**
Required

fix: model tab not always loading

---

src/app/app.module.ts
src/app/fields/checkbox/checkbox.component.html
src/app/fields/checkbox/checkbox.component.spec.ts
src/app/fields/checkbox/checkbox.component.ts
src/app/fields/form/form.component.html
src/app/fields/form/form.component.ts
src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.html
src/app/workspace/workspace-execute-dialog/workspace-execute-dialog.component.ts
src/styles/flex-styles.scss
src/styles/styles.scss

feat: move capture node checkbox next to node pool
